### ISSUE TITLE
Add recipe for Laurophyllum billet.

### ISSUE THREAD

**Issue by Anaghold** [WinternestStudios/Genesis#34]
Laurophyllum branch give 1 Laurophyllum billet.

**Comment by nabijaczleweli** [comment]
Tested this before, it *should* work (get added where all other recipes are), not sure why it doesn't

**Comment by Fararise** [comment]
Laurophyllum is counted as a bush, and it only adds the billet recipe for trees. What is the intended behavior? Is it supposed to be a bush? Is Laurophyllum the only bush that should have this recipe?
